os: linux
dist: bionic

language: go

jobs:
  include:
    - go: 1.13.x
      env:
        - ARTIFACT=true
    # - go: 1.12.x
  allow_failures:
    # - go: 1.14.x

env:
  global:
    # Enable Go Module Support
    - GO111MODULE=on

before_install:
  - go get github.com/mitchellh/gox

install:
  - # skip

script:
  - set -e
  - go get -t -v ./...
  - diff -u <(echo -n) <(gofmt -d .)
  - go vet $(go list ./... | grep -v /vendor/)
  - go test -v -race ./...
  - | # Only build binaries from the supported Go version
      if [ "${ARTIFACT}" = "true" ]; then
        CGO_ENABLED=0
        GOFLAGS=-mod=vendor
        gox -os="darwin linux windows" \
            -arch="amd64" \
            -output="release/aws-get-secret_{{.OS}}_{{.Arch}}" \
            -ldflags "-X main.GitCommit=$TRAVIS_COMMIT -X main.ReleaseVer=$TRAVIS_TAG"
            -verbose ./...;
        find release/* -type f -exec sh -c 'sha256sum {} | cut -f1 -d" " > {}.SHA256SUM' \;
        find release/* -not -name "*.SHA256SUM" -type f -print0 | xargs -0 -n 1 -I '{@}' zip -jm {@}.zip {@}
        find release/* -type f -not -name "*.SHA256SUM" -exec sh -c 'sha256sum {} | cut -f1 -d" " > {}.SHA256SUM' \;
      fi

deploy:
  provider: releases
  token:
    secure: "aRLhF7KudN02WfIOBTEhi7Snmp90Et2w6h4KHmt7pfQveeMYn6EapFrdt7KVg5aW9AQOafKsn0cP4fzMAFG6ToFjInu5F9ARV8Cj4Cf4hCsoHDGU/PkJaJmbAmn6Ea8izMjGqC+jg4scWlHUnNZ/oHhQDJH/ZTFR0Y2Uwdjeft1jWlCHNIQRcX2KiNCc8B7mLzjcdUzeDhxXG7GQH3ifogdiafve8Yus3/H/++6JpRHUaf4S7mv8yJqxK80SlIicR/BUoG0g48v4uh7zIt8xHmgOypneibgqEmiS2escm7rN+bNhz7ixCaQ7dxhksokdJ7M4IlNxM5LPBg8k6schFqSI8JUTdsghLWGBtWA0ZeopIGmphdyZnvaSY74y5MBimZCn7LGMAULTQUMkJYTZoB45yVXqDxV8N0gBdijtADZRAgQIShCXVAoPJWyF3Y5w4PfpN6Fx2vq2Loln7cf6dYi74OBDcM1pl3YJb73eVJv2GzFx3mn1d+MEikphFYa6SSODFJQ50z7yGyJ7398aS3IUe3q//aM2qSYvgoZuS8UVFE7Tdg0ANsvDeq6WnIIsSR4ItD8c3ZtJl3t2lOTqOPqxPqmPASFQRezRGENY+ixOQ3mbXX7WSFkEWyOoOhrDh51YCgKTVbXVt4erm1RMTBRtEkBY4zzjswFgwHWFwFA="
  file:
    - release/aws-get-secret_windows_amd64.exe.zip
    - release/aws-get-secret_windows_amd64.exe.SHA256SUM
    - release/aws-get-secret_windows_amd64.exe.zip.SHA256SUM
    - release/aws-get-secret_darwin_amd64
    - release/aws-get-secret_darwin_amd64.SHA256SUM
    - release/aws-get-secret_darwin_amd64.zip.SHA256SUM
    - release/aws-get-secret_linux_amd64
    - release/aws-get-secret_linux_amd64.SHA256SUM
    - release/aws-get-secret_linux_amd64.zip.SHA256SUM
  on:
    repo: bdwyertech/aws-get-secret
    tags: true
    condition: $ARTIFACT = true
