name: Go
on: [push]
jobs:

  test:
    name: Build
    strategy:
      matrix:
        go: [1.13]
    runs-on: ubuntu-latest
    container: golang:${{ matrix.go }}
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Git Info
        id: git
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

      - name: Test
        env:
          GOFLAGS: '-mod=vendor'
        run: |
          go fmt $(go list ./... | grep -v /vendor/)
          go vet $(go list ./... | grep -v /vendor/)
          go test -v -race $(go list ./... | grep -v /vendor/)

      - name: Run GoReleaser
        if: startsWith(github.ref, 'refs/tags/')
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release
          # key: ${{ secrets.GPG_CODE_SIGN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#      - name: Build
#        env:
#          CGO_ENABLED: 0
#          GOFLAGS: '-mod=vendor'
#        run: | # Only build binaries from the supported Go version
#          apt-get update && apt-get install -y zip
#          GOFLAGS='' go get -u github.com/mitchellh/gox
#          ARTIFACT='true'
#          if [ "${ARTIFACT}" = "true" ]; then
#            gox -os="darwin linux windows" \
#                -arch="amd64" \
#                -output="release/aws-get-secret_{{.OS}}_{{.Arch}}" \
#                -ldflags "-X main.GitCommit=$GITHUB_SHA -X main.ReleaseVer=${{ steps.git.outputs.SOURCE_TAG }}" \
#                -verbose ./...;
#            find release/* -type f -exec sh -c 'sha256sum {} | cut -f1 -d" " > {}.SHA256SUM' \;
#            find release/* -not -name "*.SHA256SUM" -type f -print0 | xargs -0 -n 1 -I '{@}' zip -jm {@}.zip {@}
#            find release/* -type f -not -name "*.SHA256SUM" -exec sh -c 'sha256sum {} | cut -f1 -d" " > {}.SHA256SUM' \;
#          fi
#
#      - name: Release
#        uses: softprops/action-gh-release@v1
#        if: startsWith(github.ref, 'refs/tags/')
#        with:
#          name: Release ${{ steps.git.outputs.SOURCE_TAG }}
#          files: 'release/*'
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
