name: Go
on: [push]
jobs:

  test:
    name: Build
    strategy:
      matrix:
        go: [1.13]
    runs-on: ubuntu-latest
    container: golang:${{ matrix.go }}
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Test
        env:
          GOFLAGS: '-mod=vendor'
        run: |
          go fmt $(go list ./... | grep -v /vendor/)
          go vet $(go list ./... | grep -v /vendor/)
          go test -v -race $(go list ./... | grep -v /vendor/)

      - name: Build
        run: | # Only build binaries from the supported Go version
          apt-get update && apt-get install -y zip
          go get -u github.com/mitchellh/gox
          ARTIFACT='true'
          if [ "${ARTIFACT}" = "true" ]; then
            CGO_ENABLED=0
            GOFLAGS=-mod=vendor
            gox -os="darwin linux windows" \
                -arch="amd64" \
                -output="release/aws-get-secret_{{.OS}}_{{.Arch}}" \
                -ldflags "-X main.GitCommit=$TRAVIS_COMMIT -X main.ReleaseVer=$TRAVIS_TAG" \
                -verbose ./...;
            find release/* -type f -exec sh -c 'sha256sum {} | cut -f1 -d" " > {}.SHA256SUM' \;
            find release/* -not -name "*.SHA256SUM" -type f -print0 | xargs -0 -n 1 -I '{@}' zip -jm {@}.zip {@}
            find release/* -type f -not -name "*.SHA256SUM" -exec sh -c 'sha256sum {} | cut -f1 -d" " > {}.SHA256SUM' \;
          fi

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: 'release/*'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
