name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Lint Test
      run: |
        diff -u <(echo -n) <(gofmt -d .)
        go vet $(go list ./... | grep -v /vendor/)

    - name: Test
      run: go test -v -race ./...

    - name: Build
      run: go build -v .
